services:
  - type: web
    name: moviesquad
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
